~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ó Ù Ó Ô Å Í   Á                                              Priceº   #4,500
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Labellinç Softwarå V1.0:‚     Includeó alì facilitieó foò designinç labeló  ¦ 
composinç labeì contents¬ witè á fixeä rangå oæ symboló ¦ typefaces

Epsoî  FX8µ  printer:‚  Doô matrix¬ 8° cols.¬ 16° ch./sec. draft¬ 3² ch./sec.
Neaò Letteò Quality®  Uğ tï 2µ sq® in./min. labeì printing®   Frictioî ¦ piî
feed¬ tractoò option.

Industriaì computeò specification:‚   ´ microprocessors¬  272Ë RAM¬  ² ø 800Ë 
floppù drives®    8· keù keyboard®     12¢ greeî screeî 8° ø 2µ ch. display®   
14¢ colouò monitoò foò higè resolutioî labeì display.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ó Ù Ó Ô Å Í   B                                              Priceº  #10,400
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Labellinç Softwarå V1.0º     Includeó alì facilitieó foò designinç labeló  ¦ 
composinç labeì contents¬ witè á rangå oæ symboló ¦ fonts.    Symboì editor.
Font editor.   Database and database editor.

Printroniø P30° printer:‚   Shuttlå matrix®   30° lineó/min. datá  processinç 
17¢/min. labeì printing®   Botè modeó aô uğ tï 13.5¢ wide®   Sounä reductioî 
pedestal

Industriaì computeò specification:‚   ´ microprocessors¬  784Ë RAM¬  ² ø 800Ë 
floppù drives®    8· keù keyboard®     12¢ greeî screeî 8° ø 2µ ch. display®   
14¢ colouò monitoò foò higè resolutioî labeì display.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Ó Ù Ó Ô Å Í   C                                              Priceº  #13,150
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Labellinç Softwarå V1.0º     Includeó alì facilitieó foò designinç labeló  ¦ 
composinç labeì contents¬ witè á rangå oæ symboló ¦  fonts.   Symboì editor.
Font editor.   Database and database editor.

Printroniø  P60° printer:‚  Shuttlå matrix®    60° lineó/min. datá processinç 
33¢/min. labeì printing®   Botè modeó aô uğ tï 13.5¢ wide®   Sounä reductioî 
pedestal

Industriaì computeò specification:‚    ´ microprocessors¬ 784Ë RAM¬ ± x 20.8M
Winchesteò harä disc¬  ± ø 800Ë floppù drive®   8· keù keyboard®   12¢ greeî
screeî  8° ø 2µ ch. display®    14¢ colouò monitoò foò higè resolutioî labeì
display.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
